config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'platforms#index'
  resources :chatrooms, only: [:index] do
    resources :messages, only: [:create]
  end
  get '/construct/', to: 'platforms#construct'

  # get '/others_accounts/', to: 'profiles#others_accounts'
  # get '/your_accounts/', to: 'profiles#your_accounts'
  # get '/requests/', to: 'profiles#requests'

  resources :platforms, only: [:index, :show] do
    resources :build, controller: 'platform_accounts/build', only: [:create]
  end

  resources :platform_accounts, only: [:show, :destroy, :edit, :update] do
    resources :build, controller: 'platform_accounts/build', only: [:show, :update]
  end

  resources :account_seats, only: [:create, :update]
  resources :messages, only: [:new, :create]
  resources :profiles, only: [:edit, :update, :show, :destroy] do
    resources :reviews, only: [ :new, :create ]
    resources :reports, only: [:new, :create]
  end
  resources :reviews, only: [ :destroy]
  resources :reports, only: [:index, :destroy]
  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chatrooms, only: [:index, :show]
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :messages, only: [:index, :create]
  end
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: [:show, :edit]
  def index
    @platforms = policy_scope(Platform)
  end

  def show
    authorize @platform
    @platform = Platform.find(params[:id])
    @accounts = PlatformAccount.where(platform_id: params[:id])
  end

  def edit
  end

  def update
    platform = Platform.new(strong_platform)
    platform.id = params[:id]
    platform.save
  end

  def new
    @platform = Platform.new
  end

  def create
    Platform.create(set_platform)
  end

  def construct
    skip_authorization
    @platforms = Platform.all
  end

  private

  def set_platform
    @platform = Platform.find(params[:id])
  end

  def strong_platform
    params.require(:platform).permit(:category, :name)
  end
end

app/views/platforms/construct.html.erb
<div class="title-header" id="header-smaller">
<h1 id="header1-smaller">Select a platform:</h1>
</div>

<div class="platforms-container" id="container-smaller">
<% @platforms.each do |platform|%>
  <div class="platform-cards" id="card-small">
  <%= link_to platform_build_index_path(platform), method: :post do %>
  <%= cl_image_tag platform.logo.key, width: 150, crop: :fill if platform.logo.attached? %>
  </div>
  <% end %>
<% end %>
</div>

<style>

body {
  background-color: white;
}

h1, h2, p {
  color: black;
}

.platforms-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-evenly;
  padding-left: 10%;
  padding-right: 10%;
  margin-top: -5%;
  margin-bottom: 10%;
}

.platform-cards {
  border: solid 1px #FF4949;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 150px;
  border-radius: 25px;
  margin: 1%;

}

.platform-cards {
  background-color: white;
}

.platform-cards:hover {
  transform: scale(1.1);
  transition-duration: 0.8s;
}

.title-header {
  padding-top: 5%;
  background-color: white;
  border-radius: 0% 0% 40% 40%;
  padding-bottom: 15%;
  padding-left: 20%;
  padding-right: 20%;
  text-align: center;
}

body {
  background-color: #FFEAEA;
}
/* Navbar color */

a.nav-link {
    color: #FF4949 !important;
}

#logo-text {
  color: #FF4949;
}

.navbar.navbar-expand-sm.navbar-light {
    background-color: white;
}
</style>

app/views/platforms/index.html.erb
<div class="title-header">
<h1>Welcome to Shareflix!</h1>
<h2>Open your account to the community and get access to all member's accounts.</h2>
</div>

<div class="platforms-container mb-5">
  <% @platforms.each do |platform|%>
    <div class="platform-cards">
      <%= link_to platform_path(platform.id) do %>
      <%= cl_image_tag platform.logo.key, width: 150, crop: :fill if platform.logo.attached? %>
    </div>
   <% end %>
  <% end %>

</div>

<div class="d-flex justify-content-center mb-4">
  <h3>How does Shareflix works ?</h3>
</div>

<br>

<div class="d-flex bou justify-content-center">
  <div class="list-paragraph mb-4">
    <p>1. <span class="toto">&nbsp;Join&nbsp;</span>&nbsp;the community</p><br/>
    <p>2. <span class="toto">&nbsp;Share&nbsp;</span>&nbsp;at least one account</p><br/>
    <p>3. Get <span class="toto">&nbsp;unlimlited access&nbsp;</span>&nbsp;to community's account</p>
  </div>
  <div class="artboard">
     <%= image_tag "Artboard.png" %>
  </div>
</div>


<style>

body {
  background-color: white;
}

h1, p {
  color: white;
}

.custom-container {
  min-height: 90vh;
}

.platforms-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-evenly;
    padding-left: 10%;
    padding-right: 10%;
    margin-top: -10%;
    margin-bottom: 10%;
}

.platform-cards {
    flex: 1 0 21%;
    border: solid 1px #FF4949;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 200px;
    border-radius: 25px;
    margin: 1%;

}

.platform-cards {
  background-color: white;
}

.platform-cards:hover {
    transform: scale(1.1);
    transition-duration: 0.8s;
}

.title-header {
  padding-top: 10%;
  background-color: #FF4949;
  border-radius: 0% 0% 40% 40%;
  padding-bottom: 15%;
  padding-left: 20%;
  padding-right: 20%;
  text-align: center;
}

h1 {
  color: white !important;
}

/* Navbar color */

a.nav-link {
    color: white !important;
}

#logo-text {
  color: white;
}

.navbar.navbar-expand-sm.navbar-light {
    background-color: #FF4949;
}

.list-paragraph {
  width: 480px;
  font-size: x-large;
}

.list-paragraph p {
  color: black;
  margin-bottom: 2px;
}

.artboard {
  width: 380px;
  margin-bottom: 40px;
}

.artboard img {
  object-fit: cover;
  width: 150%;
  margin-left: 10%;
  opacity: 0.8;
}

.toto {
  background-color: #FF4949;
  color: white;
}

.bou {
  margin-bottom: 32px;
  /*display: flex !important;*/
  /*justify-content: flex-around;*/
  align-items: center;
  padding-bottom: 10px;
}


</style>

app/views/platforms/show.html.erb
<div class="title-header"></div>

<div class="platform-box">
  <div id="platform-img">
    <%= cl_image_tag @platform.logo.key, width: 150, crop: :fill %>
  </div>
  <p id="platform-desc"><%= @platform.description[0..300] %></p>
</div>

<div class="cards-box">
  <% @accounts.each do |account| %>
    <% if account.seats_available.present? %>
      <div class="card-account">
        <% if account.user.photo.attached?  %>
          <%= link_to profile_path(account.user) do %>
          <%= cl_image_tag  account.user.photo.key, class: "user-profile", width: 100, height: 100, crop: :fill  %>
          <% end %>
        <% else %>
          <%= link_to profile_path(account.user) do %>
          <%= image_tag "https://i0.wp.com/ahfirstaid.org/wp-content/uploads/2014/07/avatar-placeholder.png", class: "default-profile", width: 100, height: 100, crop: :fill  %>
          <% end %>
        <% end %>
        <span class="account-title"><span><%= @platform.name %> <%= SubscriptionType.find_by(id: account.account_type).name unless SubscriptionType.find_by(id: account.account_type) == nil %></span><br/>
          <span class="shared-by">Shared by <%= account.user.first_name.capitalize %> <%= account.user.last_name.first %>.<br/>
            <% review_sum = 0 %>
            <% review_num = 0 %>
            <% stars = "" %>
            <% if account.user.review_tenants != [] %>
            <% account.user.review_tenants.each do |review| %>
              <% review_sum += review.rating.to_i %>
              <% review_num += 1 %>
            <% end %>
            <% review_avrg = review_sum / review_num %>
            <% review_avrg == nil ? "" : review_avrg.round.times do  %>
              <span>⭐️</span>
            <% end %>
            <span class="rating"> <%= review_avrg.to_f %>/5 (<%= review_num %>)</span>
            <% else %>
            <span style="font-style: italic; font-weight: 400;">No reviews</span>
            <% end %>
          </span>
        </span>
        <span class="seats"  data-toggle="tooltip" data-placement="top" title="How many seats are left before the account is full."><span class="seats_available_colorized"><%= account.seats_available == nil ? "error" : account.seats_available - AccountSeat.where(platform_account: account).where(status: 'accepted').count %></span><span style="font-size: 38px;"> Seats Left</span></span>
        <%= link_to "Join", platform_account_path(account), class: "main-button" %>
      </div>
    <% end %>
  <% end %>
</div>


<style>

.platform-box {
    display: flex;
    align-items: center;
    border: solid 2px black;
    padding: 3%;
    margin-left: 15%;
    margin-right: 15%;
    margin-top: -10%;
    background-color: white;
    border-radius: 15px;
    margin-bottom: 2%;
}

div#platform-img {
    padding: 2%;
    border-right: solid 2px lightgray;
}

#platform-desc {
  padding-left:  3%;
}

.card-account {
  display: flex;
  border: 2px solid #FF4949;
  padding: 2%;
  margin-left: 15%;
  margin-right: 15%;
  margin-bottom: 2%;
  border-radius: 15px;
  justify-content: space-between;
  align-items: center;
  background-color: white;
}

.cards-box {
  margin-bottom: 10%;
}

.shared-by {
  font-size: 0.6em;
  text-align: left;
}

.seats {
    font-size: 3em;
}

span.seats_available_colorized {
    color: #FF4949;
}

a.main-button {
    text-align: cemter;
    text-align: center;
    background-color: #FF4949;
    padding-left: 10%;
    padding-right: 10%;
    padding-top: 2%;
    padding-bottom: 2%;
    border-radius: 60px;
    color: white;
    font-weight: 600;
}

a.main-button:hover {
   text-decoration: none;
}

.account-title {
  font-size: 1.5em;
  font-weight: 500;
}

img.user-profile {
    border-radius: 50%;
}


.title-header {
  padding-top: 5%;
  background-color: #FF4949;
  border-radius: 0% 0% 40% 40%;
  padding-bottom: 15%;
  padding-left: 20%;
  padding-right: 20%;
  text-align: center;
}


.rating {
  color: black;
}

/* Navbar color */

a.nav-link {
    color: white !important;
}

#logo-text {
  color: white;
}

.navbar.navbar-expand-sm.navbar-light {
    background-color: #FF4949;
}
</style>