config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'platforms#index'
  resources :chatrooms, only: [:index] do
    resources :messages, only: [:create]
  end
  get '/construct/', to: 'platforms#construct'

  # get '/others_accounts/', to: 'profiles#others_accounts'
  # get '/your_accounts/', to: 'profiles#your_accounts'
  # get '/requests/', to: 'profiles#requests'

  resources :platforms, only: [:index, :show] do
    resources :build, controller: 'platform_accounts/build', only: [:create]
  end

  resources :platform_accounts, only: [:show, :destroy, :edit, :update] do
    resources :build, controller: 'platform_accounts/build', only: [:show, :update]
  end

  resources :account_seats, only: [:create, :update]
  resources :messages, only: [:new, :create]
  resources :profiles, only: [:edit, :update, :show, :destroy] do
    resources :reviews, only: [ :new, :create ]
    resources :reports, only: [:new, :create]
  end
  resources :reviews, only: [ :destroy]
  resources :reports, only: [:index, :destroy]
  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chatrooms, only: [:index, :show]
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :messages, only: [:index, :create]
  end
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :platform_account
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages
end

app/controllers/api/v1/chatrooms_controller.rb
class Api::V1::ChatroomsController < Api::V1::BaseController

  def index
    @chatrooms = policy_scope(Chatroom)
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    authorize(@chatroom)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = policy_scope(Chatroom)
    @message = Message.new
    respond_to do |format|
      format.html
      format.json { render json: { chatroom: @chatroom } }
    end
  end
end

app/views/chatrooms/_message.html.erb
<div class="d-flex align-items-center justify-content-around message-container">
  <div class="d-none authorid"><%= message.user.id %></div>
  <div class = " photo photo-other d-none">
    <%= link_to profile_path(message.user) do  %>
      <% if message.user.photo.attached? %>
        <%= cl_image_tag message.user.photo.key,class: "user-avatar",  width: 50, crop: :fill if message.user.photo.attached? %>
      <% else %>
        <img class = "user-avatar" src="https://i0.wp.com/ahfirstaid.org/wp-content/uploads/2014/07/avatar-placeholder.png" alt="">
      <% end %>
    <% end %>
  </div>
  <div>
    <i class="author">
      <span><strong><%= message.user.first_name %></span></strong> - <span><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></span>
    </i>
    <div class=" message d-none media-other" id="message-<%= message.id %>">
      <div class="content-msg">
        <p><%= message.content %></p>
      </div>
    </div>
  <div class="d-flex justify-content-end">
    <div class=" message d-none media-user " id="message-<%= message.id %>">
      <div class="content-msg">
        <p><%= message.content %></p>
      </div>
    </div>
     <div class = " photo photo-user d-none">
      <%= link_to profile_path(message.user) do %>
        <% if message.user.photo.attached? %>
          <%= cl_image_tag message.user.photo.key,class: "user-avatar",  width: 50, crop: :fill if message.user.photo.attached? %>
        <% else %>
          <img class = "user-avatar" src="https://i0.wp.com/ahfirstaid.org/wp-content/uploads/2014/07/avatar-placeholder.png" alt="">
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/chatrooms/index.html.erb
<div class="row chatroom-container" data-current-user-id="<%= current_user.id %>" id = "main-container" >
  <div class="col-12 col-md-4 chats" data-controller="chatrooms">
    <div class=" chatroom", id = "chatrooms">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <% @chatrooms.each do |chatroom| %>
        <span class = "chatroom<%= chatroom.id %> chatroom" data-id="<%= chatroom.id %>" data-target="chatrooms.chatroom" data-action="click->chatrooms#toto">
          <div class="elements-chatroom row">
            <div class="col-12">
              <h3 class = "chat-description"><%= chatroom.platform_account.user.first_name + "'s " + chatroom.platform_account.platform.name + " account"%></h3>
              <% platform = Platform.find(chatroom.platform_account.platform_id) %>
            </div>
            <br>
            <div class="row col-12 justify-content-between">
              <div class="photos row col-10 align-items-center">
                <% chatroom.users.each do |user|  %>
                  <div class="col-3">
                    <%= link_to profile_path(user) do  %>
                      <% if user.photo.attached? %>
                        <%= cl_image_tag user.photo.key,class: "user-avatar", crop: :fill %>
                      <% else %>
                        <img class = "user-avatar" src="https://i0.wp.com/ahfirstaid.org/wp-content/uploads/2014/07/avatar-placeholder.png" alt="">
                      <% end %>
                    <% end %>
                </div>
                <% end %>
              </div>
              <div class="col-2">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </span>
        <% end %>
        <div class="d-flex justify-content-left align-items-center" style="padding-left: 3%;">
          <%= link_to platforms_path do %>
            <i class="fa fa-home" aria-hidden="true"></i>
          <% end %>
        </div>
    </div>
  </div>
  </div>
  <div class="col-12 col-md-8 px-0 container-chat">
    <% @chatrooms.each do |chatroom| %>
      <div id="messages-<%= chatroom.id%>" data-chatroom-id="<%= chatroom.id %>" class = "d-none messages">
        <% chatroom.messages.order(:created_at).each do |message| %>
          <%= render 'chatrooms/message', message: message %>
        <% end %>
      </div>
    <% end %>
    <div class="d-none user-id"><%= current_user.id %></div>
    <div class = "d-none chatroom-selected"></div>
    <div class="d-none" data-user-id="<%= current_user.id %>"></div>

    <% message = Message.new %>
    <% @chatrooms.each do |chatroom| %>
    <div class="d-none form-chatroom form-<%= chatroom.id %>">
      <%= simple_form_for [ chatroom, message ], remote: true do |f| %>
      <div  class = "row justify-content-center align-items-center">
        <div class="col-11">
          <%= f.input :content, label: false, input_html: { class: " content-#{chatroom.id}" }, placeholder: "Write your message..." %>
        </div>
        <div class="col-1 container-button-chat">
          <div class="container-button-chat">
          <%= f.submit '⌲', class: " submit-btn-chat"%>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
</div>
<style>
  body {
    background-color: white;
    overflow: hidden;
  }
  .footer{
    display: none;
  }

  .navbar.navbar-expand-sm.navbar-light {
    display: none;
}
</style>
<%# reste à faire sur les chatrooms: -control du scroll (très rapide) ok pour la non création
                                     -Ajax (presque fait)
                                     -Front (améliorer les show des messages + chatrooms)
                                     -Checker que tout fonctionne bien Surtout le Action cable %>