config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'platforms#index'
  resources :chatrooms, only: [:index] do
    resources :messages, only: [:create]
  end
  get '/construct/', to: 'platforms#construct'

  # get '/others_accounts/', to: 'profiles#others_accounts'
  # get '/your_accounts/', to: 'profiles#your_accounts'
  # get '/requests/', to: 'profiles#requests'

  resources :platforms, only: [:index, :show] do
    resources :build, controller: 'platform_accounts/build', only: [:create]
  end

  resources :platform_accounts, only: [:show, :destroy, :edit, :update] do
    resources :build, controller: 'platform_accounts/build', only: [:show, :update]
  end

  resources :account_seats, only: [:create, :update]
  resources :messages, only: [:new, :create]
  resources :profiles, only: [:edit, :update, :show, :destroy] do
    resources :reviews, only: [ :new, :create ]
    resources :reports, only: [:new, :create]
  end
  resources :reviews, only: [ :destroy]
  resources :reports, only: [:index, :destroy]
  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chatrooms, only: [:index, :show]
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :messages, only: [:index, :create]
  end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <h4>shareflix</h4>
  <br>
  <div class="paragraph">
    <a href="">About us</a><br/>
    <a href="">Manifesto</a><br/>
    <a href="https://youtu.be/TZE9gVF1QbA">Contact</a><br/>
    <a href="https://www.lewagon.com/" target="_blank">Le Wagon</a><br/>
    <a href="https://github.com/alextouze20/shareflix" target="_blank"><i class="fab fa-github" style="color: white; font-size: 1.5em; margin-top: 1%;"></i></a>
    <br>
  </div>
  <div class="signature">
    <p>made with <span>amour</span> at Le Wagon by <a href="https://github.com/patriciablbn" target="_blank">patriciablbn</a>, <a href="https://github.com/CorentinBourda" target="_blank">CorentinBourda</a>, <a href="https://github.com/OctaveC" target="_blank">OctaveC</a> & <a href="https://github.com/alextouze20/" target="_blank">alextouze</a></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <%= link_to "/", class: "navbar-brand" do %>
    <span id="logo-text">shareflix</span>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% pending_request = AccountSeat.where(platform_account: current_user.platform_accounts).where(status: 'pending') %>
        <% if pending_request != [] %>
        <li class="nav-item">
          <%= link_to "Pending requests: #{pending_request.count}", profile_path(current_user, tab: "requests"), class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Add an account', construct_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", chatrooms_path(), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://i0.wp.com/ahfirstaid.org/wp-content/uploads/2014/07/avatar-placeholder.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "My personal accounts", profile_path(current_user, tab: "accounts"), class: "dropdown-item" %>
            <%= link_to "Borrowed accounts", profile_path(current_user, tab: "borrowed_accounts"), class: "dropdown-item" %>
            <%= link_to "My requests", profile_path(current_user, tab: "requests"), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>